name: Deployment pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches: [master]
    types: [opened, synchronize]

jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
     - uses: actions/checkout@v2
     - uses: actions/setup-node@v1
       with:
         node-version: '12.x'
     - name: npm install
       run: npm install
     - name: lint
       run: |
         npm run eslint
     - name: build
       run: |
         npm run build
     - name: test
       run: |
         npm run test
     - name: e2e tests
       uses: cypress-io/github-action@v2
       with:
         command: npm run test:e2e
         start: npm run start-prod
         wait-on: http://localhost:5000
# Only bump version on pull to master
  tag:
   if: ${{ github.event_name == 'push' }}
   runs-on: ubuntu-18.04
   needs: test
   steps:
   - uses: actions/checkout@v2
   - name: Bump version and push tag
     uses: anothrNick/github-tag-action@1.33.0
     env:
       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       DEFAULT_BUMP: "patch"


# https://wsd.cs.aalto.fi/19-continuous-integration-and-deployment/2-continuous-deployment/
  deploy: 
    if: ${{ github.event_name == 'push' }}
    runs-on: ubuntu-18.04
    needs: [test, tag]
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with: 
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "quiet-shore-77013"
          heroku_email: "vkoskela@gmail.com"
          healthcheck: "https://quiet-shore-77013.herokuapp.com/version"
          checkstring: "4"
          rollbackonhealthcheckfailed: true
